- name: Install the repository RPM
  ansible.builtin.dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-10-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: true
  become: true
- name: Install PostgreSQL
  ansible.builtin.dnf:
    name: postgresql18-server
    state: present
  become: true
- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version
- name: Initialize the database cluster
  ansible.builtin.command: /usr/pgsql-18/bin/postgresql-18-setup initdb
  become: true
  when: not pgdata_dir_version.stat.exists
- name: Enable and start postgresql service
  ansible.builtin.service:
    name: postgresql-18
    state: restarted
    enabled: true
  become: true
